export const INDIAN_CITIES = [
  "Mumbai", "Delhi", "Bangalore", "Hyderabad", "Ahmedabad", "Chennai", "Kolkata", "Surat", "Pune", "Jaipur",
  "Lucknow", "Kanpur", "Nagpur", "Indore", "Thane", "Bhopal", "Visakhapatnam", "Pimpri-Chinchwad", "Patna",
  "Vadodara", "Ghaziabad", "Ludhiana", "Agra", "Nashik", "Faridabad", "Meerut", "Rajkot", "Kalyan-Dombivli",
  "Vasai-Virar", "Varanasi", "Srinagar", "Aurangabad", "Dhanbad", "Amritsar", "Navi Mumbai", "Allahabad",
  "Ranchi", "Howrah", "Coimbatore", "Jabalpur", "Gwalior", "Vijayawada", "Jodhpur", "Madurai", "Raipur",
  "Kota", "Guwahati", "Chandigarh", "Solapur", "Hubli-Dharwad"
].sort();

export const CITY_COLLEGES: { [key: string]: string[] } = {
  "Mumbai": ["IIT Bombay", "VJTI", "SPIT", "KJ Somaiya", "Thakur College", "NMIMS", "St. Francis"],
  "Delhi": ["IIT Delhi", "DTU", "NSUT", "IIIT Delhi", "Miranda House", "SRCC", "Hansraj College"],
  "Bangalore": ["IISc", "RV College of Engineering", "BMS College of Engineering", "PES University", "Ramaiah Institute", "Christ University"],
  "Hyderabad": ["IIT Hyderabad", "IIIT Hyderabad", "BITS Pilani Hyderabad", "JNTU Hyderabad", "Osmania University", "VNR VJIET"],
  "Ahmedabad": ["IIT Gandhinagar", "Nirma University", "DA-IICT", "LD College of Engineering", "Gujarat University"],
  "Chennai": ["IIT Madras", "Anna University", "SSN College of Engineering", "Loyola College", "Madras Christian College", "CEG Guindy"],
  "Kolkata": ["IIT Kharagpur", "Jadavpur University", "IIEST Shibpur", "Presidency University", "St. Xavier's College"],
  "Surat": ["SVNIT Surat", "SCET Surat", "Government Engineering College, Surat"],
  "Pune": ["COEP Pune", "PICT", "VIT Pune", "Symbiosis Institute of Technology", "Fergusson College"],
  "Jaipur": ["MNIT Jaipur", "BITS Pilani", "Manipal University Jaipur", "Rajasthan University", "JECRC"],
  "Lucknow": ["IIT Lucknow", "IIM Lucknow", "University of Lucknow", "BBD University"],
  "Kanpur": ["IIT Kanpur", "HBTI Kanpur", "CSJM University"],
  "Nagpur": ["VNIT Nagpur", "IIIT Nagpur", "Ramdeobaba College of Engineering"],
  "Indore": ["IIT Indore", "IIM Indore", "SGSITS Indore"],
  "Thane": ["Thakur College of Engineering", "K.J. Somaiya", "VPM Polytechnic"],
  "Bhopal": ["MANIT Bhopal", "IISER Bhopal", "UIT RGPV"],
  "Visakhapatnam": ["IIT Visakhapatnam", "Andhra University", "GITAM University"],
  "Pimpri-Chinchwad": ["PCCOE Pune", "DY Patil College of Engineering", "AISSMS"],
  "Patna": ["IIT Patna", "NIT Patna", "Patna University"],
  "Vadodara": ["MS University of Baroda", "IITRAM", "Parul University"],
  "Ghaziabad": ["ABES Engineering College", "KIET Group of Institutions", "Ajay Kumar Garg Engineering College"],
  "Ludhiana": ["Guru Nanak Dev Engineering College", "PAU Ludhiana", "PCTE Group of Institutes"],
  "Agra": ["Dayalbagh Educational Institute", "Agra College", "RBS College"],
  "Nashik": ["KK Wagh Institute of Engineering", "MET Bhujbal Knowledge City", "Sandip University"],
  "Faridabad": ["JC Bose University", "Manav Rachna University", "Lingaya's Vidyapeeth"],
  "Meerut": ["MIET Meerut", "Chaudhary Charan Singh University", "IIMT University"],
  "Rajkot": ["Marwadi University", "Atmiya University", "Darshan University"],
  "Kalyan-Dombivli": ["Model College", "K.M. Agrawal College", "Pendharkar College"],
  "Vasai-Virar": ["VIVA Institute of Technology", "St. John College of Engineering", "Viva College"],
  "Varanasi": ["IIT BHU", "Banaras Hindu University", "MGKVP"],
  "Srinagar": ["NIT Srinagar", "University of Kashmir", "Islamic University of Science & Technology"],
  "Aurangabad": ["Government College of Engineering, Aurangabad", "Jawaharlal Nehru Engineering College", "Deogiri College"],
  "Dhanbad": ["IIT (ISM) Dhanbad", "BIT Sindri", "Dhanbad Engineering College"],
  "Amritsar": ["IIM Amritsar", "Guru Nanak Dev University", "Khalsa College"],
  "Navi Mumbai": ["SIES Graduate School of Technology", "Fr. C. Rodrigues Institute of Technology", "DY Patil University"],
  "Allahabad": ["IIIT Allahabad", "University of Allahabad", "MNNIT Allahabad"],
  "Ranchi": ["BIT Mesra", "IIM Ranchi", "Ranchi University"],
  "Howrah": ["IIEST Shibpur", "Bengal Engineering College", "Narula Institute of Technology"],
  "Coimbatore": ["PSG College of Technology", "Coimbatore Institute of Technology", "Amrita Vishwa Vidyapeetham"],
  "Jabalpur": ["PDPM IIITDM Jabalpur", "Jabalpur Engineering College", "GEC Jabalpur"],
  "Gwalior": ["ABV-IIITM Gwalior", "MITS Gwalior", "ITM University Gwalior"],
  "Vijayawada": ["VR Siddhartha Engineering College", "KL University", "Andhra Loyola College"],
  "Jodhpur": ["IIT Jodhpur", "JNVU Jodhpur", "MBM Engineering College"],
  "Madurai": ["Thiagarajar College of Engineering", "Madurai Kamaraj University", "Lady Doak College"],
  "Raipur": ["IIT Bhilai", "NIT Raipur", "Hidayatullah National Law University"],
  "Kota": ["University of Kota", "Government Engineering College, Kota", "Career Point University"],
  "Guwahati": ["IIT Guwahati", "NIT Silchar", "Gauhati University"],
  "Chandigarh": ["PEC Chandigarh", "UIET Panjab University", "Panjab University"],
  "Solapur": ["Walchand Institute of Technology", "SKN Sinhgad College of Engineering", "Solapur University"],
  "Hubli-Dharwad": ["KLE Technological University", "SDM College of Engineering and Technology", "University of Agricultural Sciences"]
};
